name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pymediainfo pillow
    
    - name: Download and setup MediaInfo for macOS
      run: |
        curl -L -o MediaInfo.dmg https://mediaarea.net/download/binary/mediainfo/23.10/MediaInfo_CLI_23.10_Mac.dmg
        hdiutil attach MediaInfo.dmg
        # Install the MediaInfo package
        sudo installer -pkg "/Volumes/MediaInfo/mediainfo.pkg" -target /
        hdiutil detach "/Volumes/MediaInfo"
        # The mediainfo binary should now be available in /usr/local/bin/
        # Copy it to our project directory
        cp /usr/local/bin/mediainfo ./mediainfo
        chmod +x ./mediainfo
    
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --onedir --windowed \
          --name="百度素材初审器" \
          --icon=app_icon.ico \
          --add-data="mediainfo:mediainfo" \
          media_analyzer_app.py
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v4
      with:
        name: 百度素材初审器-macOS
        path: dist/百度素材初审器.app