name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pymediainfo pillow
    
    - name: Download and setup MediaInfo for macOS
      run: |
        curl -L -o MediaInfo.dmg https://mediaarea.net/download/binary/mediainfo/23.10/MediaInfo_CLI_23.10_Mac.dmg
        hdiutil attach MediaInfo.dmg
        # Install the MediaInfo package
        sudo installer -pkg "/Volumes/MediaInfo/mediainfo.pkg" -target /
        hdiutil detach "/Volumes/MediaInfo"
        # The mediainfo binary should now be available in /usr/local/bin/
        # Copy it to our project directory
        cp /usr/local/bin/mediainfo ./mediainfo
        chmod +x ./mediainfo
    
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --onedir --windowed \
          --name="百度素材初审器" \
          --icon=app_icon.ico \
          --add-data="mediainfo:mediainfo" \
          media_analyzer_app.py
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v4
      with:
        name: BaiduMediaAnalyzer-macOS
        path: dist/百度素材初审器.app

    ## 如何下载macOS应用包

    1. **从GitHub Actions下载**：
       - 进入你的GitHub仓库页面
       - 点击顶部的 "Actions" 标签
       - 找到最新的成功构建（绿色勾号）
       - 点击进入该构建详情页面
       - 在页面底部的 "Artifacts" 部分，你会看到 "百度素材初审器-macOS"
       - 点击下载，会得到一个zip文件
       - 解压后就是 "百度素材初审器.app" 应用包
    
    ## 没有macOS环境如何测试
    
    由于你没有macOS环境，有以下几种测试方案：
    
    ### 1. 虚拟机方案
    - 使用VMware或VirtualBox安装macOS虚拟机
    - 在虚拟机中测试应用
    - **注意**：这可能违反Apple的许可协议，仅供开发测试用途
    
    ### 2. 云端macOS服务
    - 使用MacStadium、AWS EC2 Mac实例等云服务
    - 租用macOS环境进行测试
    - 成本较高但合法合规
    
    ### 3. 请朋友帮忙测试
    - 找有Mac电脑的朋友帮忙测试
    - 发送应用包给他们，让他们反馈使用情况
    
    ### 4. GitHub Actions自动化测试
    可以在GitHub Actions中添加基本的功能测试：
    
    - name: Test macOS App (Basic)
      run: |
        # 检查应用包是否正确生成
        ls -la dist/
        # 检查应用包结构
        ls -la "dist/百度素材初审器.app/Contents/"
        # 尝试运行应用（无GUI模式下的基本检查）
        # 注意：这只能做基本检查，不能测试GUI功能